### ISSUE TITLE
Roles needed to run rpCheckup

### ISSUE THREAD

**Issue by securitysamurai** [goldfiglabs/rpCheckup#6]
What role(s) does the user require in order to run all the checks? I'm getting the following error:

```
sudo go run main.go
INFO[0000] Running postgres                             
INFO[0000] Waiting for postgres to be healthy           
INFO[0032] Postgres is healthy                          
panic: no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed

goroutine 1 [running]:
main.main()
	/home/ec2-user/rpCheckup/main.go:214 +0xef3
exit status 2
```
From experience typically when running such tools the SecurityAudit and/or Read-Only is required.

**Comment by gsoltis** [comment]
I'll add some documentation around the required permissions. 

In the mean time, `SecurityAudit` and `ViewOnlyAccess` cover most of it, but unfortunately not all. You will also need:
 - `apigateway:GetRestApis`
 - `efs:Describe*`
 - `acm-pca:List*`
 - `acm-pca:GetPolicy`

However, from the error you are getting, it looks like you are running on a vm with a metadata server, but perhaps don't have an instance profile / role attached?

**Comment by vikrum** [comment]
Side note: the tool doesn't need `sudo` for invocation.

**Comment by securitysamurai** [comment]
So I have my AWS creds in the .aws/credentials file, including any info in the config file. I. can run the prowler tool, with thte same credentials, without any issues. The user I'm using has substantial privileges, so that shouldn't be an issue.  
I use `sudo` since it's a rough install and it needs docker for postgress. Docker by default needs root, correct? 

I'm still getting the following error. I'm not a big goLang user, so not sure if Go isn't seeing my aws creds or what. 
```
 sudo go run main.go
INFO[0000] Running postgres                             
INFO[0001] Waiting for postgres to be healthy           
INFO[0033] Postgres is healthy                          
panic: no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed

goroutine 1 [running]:
main.main()
	/home/ec2-user/rpCheckup/main.go:214 +0xef3
exit status 2
```

**Comment by gsoltis** [comment]
You shouldn't need `sudo` to just run docker images. The docker daemon runs with root privileges, and install needs root privileges, but asking it to run a container does not. Can you try without sudo and see if that makes a difference? Perhaps your credentials aren't being found due to the use of `sudo`.

**Comment by securitysamurai** [comment]
Received this error earlier:
```
go run main.go
INFO[0000] Running postgres                             
panic: Failed to pull image: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=postgres&tag=13-alpine": dial unix /var/run/docker.sock: connect: permission denied

goroutine 1 [running]:
main.main()
	/home/ec2-user/rpCheckup/main.go:209 +0xf05
exit status 2
```

**Comment by gsoltis** [comment]
Ah, you are right, by default docker is root-only on linux. I had done the following a while ago and forgot about it: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user Note that in step 3, they give you can option where you can likely get away without restarting or logout/login.

If you want to keep docker root-only, you'll need to make sure the aws credentials are available as root. I *think* that just entails copying your user's `.aws` directory to root's `$HOME` directory.

**Comment by gsoltis** [comment]
@securitysamurai are you using SSO credentials, by any chance?

**Comment by securitysamurai** [comment]
no SSO creds

**Comment by gsoltis** [comment]
Hmm, I'm a bit stumped then. Were you able to run `sudo aws sts get-caller-identity`?

**Comment by securitysamurai** [comment]
I can run the `aws sts get-caller-identity` without `sudo`. If I used `sudo` I get an error.  
So I did a  `sudo aws config` and it's running. So seems the setup of docker as non-root should be done. Or I messed up the install somehow.

**Comment by gsoltis** [comment]
Glad to hear it's running. It seems like it was just a mismatch between which user can access docker and which user can access the AWS credentials. 

Let me know how it goes!

**Comment by gsoltis** [comment]
I've updated the code to give a friendlier error message to indicate that the problem is missing AWS credentials
